export { default as Home } from "./Home";
export { default as Cart } from "./Cart";
export { default as Blog } from "./Blogs";
export { default as DetailBlog } from "./DetailBlog";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as Checkout } from "./Checkout";
export { default as Animal } from "./Animals";
export { default as Search } from "./Search";
